---
- name: Reglas de Firewall Ubuntu
  hosts: ubuntu
  become: true

  tasks:

    - name: Habilitamos UFW y bloqueamos el trafico
      community.general.ufw:
        state: enabled
        policy: deny
        direction: incoming

    - name: Permitir SSH en UFW
      community.general.ufw:
        rule: allow
        name: OpenSSH

    - name: Copiar clave pública de sysadmin
      ansible.builtin.copy:
        src: /home/sysadmin/.ssh/id_rsa.pub
        dest: /home/sysadmin/.ssh/authorized_keys
        owner: sysadmin
        group: sysadmin
        mode: '0600'

    - name: Validar clave pública del usuario sysadmin en servidor
      ansible.posix.authorized_key:
        user: sysadmin
        state: present
        key: "{{ lookup('file', '/home/sysadmin/.ssh/id_rsa.pub') }}"          

    - name: Deshabilitar autenticación por contraseña en SSH
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
      notify: Reiniciar ssh

  handlers:

    - name: Reiniciar ssh
      ansible.builtin.service:
        name: ssh
        state: restarted

