---
- name: Apache web server en CenOS
  hosts: centos
  become: true

  tasks:

  - name: Instalacion de Apache
    ansible.builtin.yum:
      name: httpd
      state: present

  - name: Servicio apache iniciado
    ansible.builtin.systemd_service:
      name: httpd
      state: started
      enabled: true

  - name: Agregar servicios al firewall
    ansible.posix.firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: true
      immediate: true
    loop: [http, https]
     
  - name: Crear el directorio raíz del sitio www.ejemplo.com.uy
    ansible.builtin.file:
      path: "/var/www/www.ejemplo.com.uy/html"
      state: directory
      owner: apache
      group: apache
      mode: '0775'      
        
  - name: Pagina indice generada por template
    ansible.builtin.template:
      src: ../templates/index.j2
      dest: "/var/www/www.ejemplo.com.uy/html/index.html"
      owner: apache
      group: apache
      mode: '0644'

  - name: Crear directorio para VirtualHost
    ansible.builtin.file:
      path: /etc/httpd/vhost.d
      state: directory
      owner: root
      group: root
      mode: '0755'        

  - name: Configurar el VirtualHost de www.ejemplo.com.uy
    ansible.builtin.template:
      src: ../templates/virtualhost.j2
      dest: "/etc/httpd/vhost.d/www.ejemplo.com.uy.conf"
      owner: root
      group: root
      mode: '0644'
    notify: Reiniciar apache

  - name: Agregar virtualHost
    ansible.builtin.lineinfile:
     path: /etc/hosts
     line: "10.10.1.12 www.ejemplo.com.uy"
     state: present
    delegate_to: localhost
    connection: local

  - name: Modificar configuración de apache
    ansible.builtin.lineinfile:
      path: /etc/httpd/conf/httpd.conf
      line: "IncludeOptional /etc/httpd/vhost.d/*.conf"
    notify: Reiniciar apache       

  handlers:
  - name: Reiniciar apache
    ansible.builtin.systemd_service:
      name: httpd
      state: restarted
